[main]
snipeit_url = "https://inventory.seemoo.tu-darmstadt.de"
listen_ip = "127.0.0.1"
listen_port = 8000
admin_user = ""
admin_password = ""

[db]
ip = "127.0.0.1"
user = "root"
password = "root"
name = "LARS"